version: "3.8"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    image: nginx:latest
    ports:
      - "0.0.0.0:81:81"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf