version: "3.8"
services:
  nginx:
    container_name: nginx
    hostname: nginx
    restart: always
    image: nginx:latest
    network_mode: host
    # ports:
      #  - 0.0.0.0:80:80
      #  - 0.0.0.0:443:443
    volumes:
      - ./default.local.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs:ro
