artifactory:
  consoleLog: true
# nginx:
#   http:
#     externalPort: 82
#   https:
#     externalPort: 445
databaseUpgradeReady: true

postgresql:
  enabled: false
database:
  # This assumes PostgreSQL is installed on the host. Otherwise, change this URL
  # so it points correctly to the PostgreSQL container (don't forget to expose the port)
  url: jdbc:postgresql://postgres:5432/artifactory-asia
  type: postgresql
  driver: org.postgresql.Driver
  user: postgres
  # TODO: Change this to be your PostgreSQL's root password
  password: isaac
